# -*- mode: python ; coding: utf-8 -*-

# 完全排除matplotlib模块及其所有子模块
excludedimports = [
    'matplotlib',
    'matplotlib.pyplot',
    'matplotlib.backends',
    'matplotlib.figure',
    'matplotlib.axes',
    'matplotlib.patches',
    'matplotlib.lines',
    'matplotlib.text',
    'matplotlib.image',
    'matplotlib.collections',
    'matplotlib.transforms',
    'matplotlib.path',
    'matplotlib.patches',
    'matplotlib.widgets',
    'matplotlib.animation',
    'matplotlib.sphinxext',
    'matplotlib.tests',
    'matplotlib.testing',
    'matplotlib.cbook',
    'matplotlib.cm',
    'matplotlib.colors',
    'matplotlib.dates',
    'matplotlib.dviread',
    'matplotlib.font_manager',
    'matplotlib.gridspec',
    'matplotlib.legend',
    'matplotlib.legend_handler',
    'matplotlib.markers',
    'matplotlib.mathtext',
    'matplotlib.mlab',
    'matplotlib.offsetbox',
    'matplotlib.patches',
    'matplotlib.quiver',
    'matplotlib.sankey',
    'matplotlib.scale',
    'matplotlib.spines',
    'matplotlib.style',
    'matplotlib.table',
    'matplotlib.ticker',
    'matplotlib.tight_layout',
    'matplotlib.tri',
    'matplotlib.units',
    'matplotlib.widgets'
] 